"""Core tables and ownership constraints"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_core"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "listings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_listing_id", sa.String(length=128), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("make", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("generation", sa.String(length=100), nullable=True),
        sa.Column("body_type", sa.String(length=100), nullable=True),
        sa.Column("engine_type", sa.String(length=100), nullable=True),
        sa.Column("transmission", sa.String(length=100), nullable=True),
        sa.Column("drive_type", sa.String(length=100), nullable=True),
        sa.Column("steering_wheel", sa.String(length=100), nullable=True),
        sa.Column("color", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("power_hp", sa.Integer(), nullable=True),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("owners_count", sa.Integer(), nullable=True),
        sa.Column("engine_volume", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("seller_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "source_metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "field_observed_at", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("normalization_version", sa.String(length=40), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("status IN ('ACTIVE','REMOVED','UNKNOWN')", name="listing_status"),
        sa.CheckConstraint("mileage_km IS NULL OR mileage_km >= 0", name="listing_mileage"),
        sa.CheckConstraint("price IS NULL OR price >= 0", name="listing_price"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listings")),
        sa.UniqueConstraint("source", "source_listing_id", name=op.f("uq_listings_source")),
    )
    op.create_index(
        "ix_listings_candidates", "listings", ["make", "model", "year", "mileage_km"], unique=False
    )
    op.create_table(
        "login_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_login_limits")),
    )
    op.create_table(
        "source_health",
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.PrimaryKeyConstraint("source", name=op.f("pk_source_health")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=10), server_default="user", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user','admin')", name="user_role"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("uq_users_username_lower", "users", [sa.literal_column("lower(username)")], unique=True)
    op.create_table(
        "worker_heartbeats",
        sa.Column("worker_id", sa.String(length=80), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("worker_id", name=op.f("pk_worker_heartbeats")),
    )
    op.create_table(
        "listing_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("listing_version", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("mileage_km", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("description_hash", sa.String(length=64), nullable=True),
        sa.Column("description_text_on_change", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_snapshots_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_snapshots")),
        sa.UniqueConstraint("listing_id", "listing_version", name=op.f("uq_listing_snapshots_listing_id")),
    )
    op.create_index(
        op.f("ix_listing_snapshots_listing_id"), "listing_snapshots", ["listing_id"], unique=False
    )
    op.create_table(
        "saved_searches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("enabled_sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("refresh_interval_seconds", sa.Integer(), server_default="1500", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_manual_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("refresh_interval_seconds >= 1200", name="search_interval"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_searches_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_searches")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_saved_searches_id")),
    )
    op.create_index(op.f("ix_saved_searches_user_id"), "saved_searches", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_digest", sa.String(length=64), nullable=False),
        sa.Column("csrf_token", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_digest", name=op.f("uq_sessions_token_digest")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "vehicle_clusters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("representative_listing_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["representative_listing_id"],
            ["listings.id"],
            name=op.f("fk_vehicle_clusters_representative_listing_id_listings"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_vehicle_clusters_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vehicle_clusters")),
        sa.UniqueConstraint("id", "user_id", name=op.f("uq_vehicle_clusters_id")),
    )
    op.create_index(
        op.f("ix_vehicle_clusters_representative_listing_id"),
        "vehicle_clusters",
        ["representative_listing_id"],
        unique=False,
    )
    op.create_index(op.f("ix_vehicle_clusters_user_id"), "vehicle_clusters", ["user_id"], unique=False)
    op.create_table(
        "cluster_memberships",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("attached_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cluster_id", "user_id"],
            ["vehicle_clusters.id", "vehicle_clusters.user_id"],
            name=op.f("fk_cluster_memberships_cluster_id_user_id_vehicle_clusters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], name=op.f("fk_cluster_memberships_listing_id_listings")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cluster_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "listing_id", name=op.f("pk_cluster_memberships")),
    )
    op.create_index(
        op.f("ix_cluster_memberships_cluster_id"), "cluster_memberships", ["cluster_id"], unique=False
    )
    op.create_index(
        op.f("ix_cluster_memberships_listing_id"), "cluster_memberships", ["listing_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=True),
        sa.Column("listing_id", sa.UUID(), nullable=True),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("event_key", sa.String(length=200), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], name=op.f("fk_events_listing_id_listings"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_events_search_id_saved_searches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["listing_snapshots.id"],
            name=op.f("fk_events_snapshot_id_listing_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
        sa.UniqueConstraint("user_id", "event_key", name=op.f("uq_events_user_id")),
    )
    op.create_index(op.f("ix_events_listing_id"), "events", ["listing_id"], unique=False)
    op.create_index(op.f("ix_events_search_id"), "events", ["search_id"], unique=False)
    op.create_index(op.f("ix_events_snapshot_id"), "events", ["snapshot_id"], unique=False)
    op.create_index(
        "ix_events_user_date",
        "events",
        ["user_id", sa.literal_column("occurred_at DESC"), "id"],
        unique=False,
    )
    op.create_index(op.f("ix_events_user_id"), "events", ["user_id"], unique=False)
    op.create_table(
        "saved_search_source_states",
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("last_result_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_saved_search_source_states_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("search_id", "source", name=op.f("pk_saved_search_source_states")),
    )
    op.create_table(
        "search_listings",
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("match_state", sa.String(length=20), nullable=False),
        sa.Column("unknown_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"], ["listings.id"], name=op.f("fk_search_listings_listing_id_listings")
        ),
        sa.ForeignKeyConstraint(
            ["search_id", "user_id"],
            ["saved_searches.id", "saved_searches.user_id"],
            name=op.f("fk_search_listings_search_id_user_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_search_listings_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_search_listings_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("search_id", "listing_id", name=op.f("pk_search_listings")),
    )
    op.create_index(op.f("ix_search_listings_listing_id"), "search_listings", ["listing_id"], unique=False)
    op.create_index(op.f("ix_search_listings_user_id"), "search_listings", ["user_id"], unique=False)
    op.create_table(
        "search_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filters_version", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=20), server_default="pending", nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["search_id", "user_id"],
            ["saved_searches.id", "saved_searches.user_id"],
            name=op.f("fk_search_runs_search_id_user_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_search_runs_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_search_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_runs")),
    )
    op.create_index(op.f("ix_search_runs_search_id"), "search_runs", ["search_id"], unique=False)
    op.create_index(op.f("ix_search_runs_user_id"), "search_runs", ["user_id"], unique=False)
    op.create_table(
        "refresh_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("search_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("state", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column("attempt", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.CheckConstraint("state IN ('queued','running','complete','failed')", name="job_state"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["search_runs.id"],
            name=op.f("fk_refresh_jobs_run_id_search_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["saved_searches.id"],
            name=op.f("fk_refresh_jobs_search_id_saved_searches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_jobs")),
        sa.UniqueConstraint("run_id", "source", name=op.f("uq_refresh_jobs_run_id")),
    )
    op.create_index(
        "ix_jobs_ready",
        "refresh_jobs",
        ["not_before"],
        unique=False,
        postgresql_where=sa.text("state = 'queued'"),
    )
    op.create_index(op.f("ix_refresh_jobs_run_id"), "refresh_jobs", ["run_id"], unique=False)
    op.create_index(op.f("ix_refresh_jobs_search_id"), "refresh_jobs", ["search_id"], unique=False)
    op.create_index(
        "uq_jobs_active",
        "refresh_jobs",
        ["search_id", "source"],
        unique=True,
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_jobs_active",
        table_name="refresh_jobs",
        postgresql_where=sa.text("state IN ('queued', 'running')"),
    )
    op.drop_index(op.f("ix_refresh_jobs_search_id"), table_name="refresh_jobs")
    op.drop_index(op.f("ix_refresh_jobs_run_id"), table_name="refresh_jobs")
    op.drop_index("ix_jobs_ready", table_name="refresh_jobs", postgresql_where=sa.text("state = 'queued'"))
    op.drop_table("refresh_jobs")
    op.drop_index(op.f("ix_search_runs_user_id"), table_name="search_runs")
    op.drop_index(op.f("ix_search_runs_search_id"), table_name="search_runs")
    op.drop_table("search_runs")
    op.drop_index(op.f("ix_search_listings_user_id"), table_name="search_listings")
    op.drop_index(op.f("ix_search_listings_listing_id"), table_name="search_listings")
    op.drop_table("search_listings")
    op.drop_table("saved_search_source_states")
    op.drop_index(op.f("ix_events_user_id"), table_name="events")
    op.drop_index("ix_events_user_date", table_name="events")
    op.drop_index(op.f("ix_events_snapshot_id"), table_name="events")
    op.drop_index(op.f("ix_events_search_id"), table_name="events")
    op.drop_index(op.f("ix_events_listing_id"), table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_cluster_memberships_listing_id"), table_name="cluster_memberships")
    op.drop_index(op.f("ix_cluster_memberships_cluster_id"), table_name="cluster_memberships")
    op.drop_table("cluster_memberships")
    op.drop_index(op.f("ix_vehicle_clusters_user_id"), table_name="vehicle_clusters")
    op.drop_index(op.f("ix_vehicle_clusters_representative_listing_id"), table_name="vehicle_clusters")
    op.drop_table("vehicle_clusters")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_saved_searches_user_id"), table_name="saved_searches")
    op.drop_table("saved_searches")
    op.drop_index(op.f("ix_listing_snapshots_listing_id"), table_name="listing_snapshots")
    op.drop_table("listing_snapshots")
    op.drop_table("worker_heartbeats")
    op.drop_index("uq_users_username_lower", table_name="users")
    op.drop_table("users")
    op.drop_table("source_health")
    op.drop_table("login_limits")
    op.drop_index("ix_listings_candidates", table_name="listings")
    op.drop_table("listings")
    # ### end Alembic commands ###
