"""dedup fingerprints decisions and audit"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "00af18fb3260"
down_revision = "0001_core"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_operations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_cluster_operations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_operations")),
    )
    op.create_index(op.f("ix_cluster_operations_user_id"), "cluster_operations", ["user_id"], unique=False)
    op.create_table(
        "listing_fingerprints",
        sa.Column("listing_id", sa.UUID(), nullable=False),
        sa.Column("photos", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
            name=op.f("fk_listing_fingerprints_listing_id_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("listing_id", name=op.f("pk_listing_fingerprints")),
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("left_id", sa.UUID(), nullable=False),
        sa.Column("right_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("left_id < right_id", name="canonical_pair"),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["listings.id"],
            name=op.f("fk_duplicate_candidates_left_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["listings.id"],
            name=op.f("fk_duplicate_candidates_right_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "left_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_duplicate_candidates_user_id_left_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "right_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_duplicate_candidates_user_id_right_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_duplicate_candidates_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_candidates")),
        sa.UniqueConstraint("user_id", "left_id", "right_id", name=op.f("uq_duplicate_candidates_user_id")),
    )
    op.create_index(
        op.f("ix_duplicate_candidates_left_id"), "duplicate_candidates", ["left_id"], unique=False
    )
    op.create_index(
        op.f("ix_duplicate_candidates_right_id"), "duplicate_candidates", ["right_id"], unique=False
    )
    op.create_index(
        op.f("ix_duplicate_candidates_user_id"), "duplicate_candidates", ["user_id"], unique=False
    )
    op.create_table(
        "duplicate_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("left_id", sa.UUID(), nullable=False),
        sa.Column("right_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("decision IN ('same','different')", name="manual_decision"),
        sa.CheckConstraint("left_id < right_id", name="canonical_pair"),
        sa.ForeignKeyConstraint(
            ["left_id"],
            ["listings.id"],
            name=op.f("fk_duplicate_decisions_left_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["listings.id"],
            name=op.f("fk_duplicate_decisions_right_id_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "left_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_duplicate_decisions_user_id_left_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "right_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_duplicate_decisions_user_id_right_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_duplicate_decisions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_decisions")),
    )
    op.create_index(op.f("ix_duplicate_decisions_left_id"), "duplicate_decisions", ["left_id"], unique=False)
    op.create_index(
        op.f("ix_duplicate_decisions_right_id"), "duplicate_decisions", ["right_id"], unique=False
    )
    op.create_index(op.f("ix_duplicate_decisions_user_id"), "duplicate_decisions", ["user_id"], unique=False)
    op.create_index(
        "uq_decisions_active",
        "duplicate_decisions",
        ["user_id", "left_id", "right_id"],
        unique=True,
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.create_table(
        "relist_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("old_id", sa.UUID(), nullable=False),
        sa.Column("new_id", sa.UUID(), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_id"], ["listings.id"], name=op.f("fk_relist_links_new_id_listings"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["old_id"], ["listings.id"], name=op.f("fk_relist_links_old_id_listings"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "new_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_relist_links_user_id_new_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "old_id"],
            ["cluster_memberships.user_id", "cluster_memberships.listing_id"],
            name=op.f("fk_relist_links_user_id_old_id_cluster_memberships"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_relist_links_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relist_links")),
        sa.UniqueConstraint("user_id", "old_id", "new_id", name=op.f("uq_relist_links_user_id")),
    )
    op.create_index(op.f("ix_relist_links_new_id"), "relist_links", ["new_id"], unique=False)
    op.create_index(op.f("ix_relist_links_old_id"), "relist_links", ["old_id"], unique=False)
    op.create_index(op.f("ix_relist_links_user_id"), "relist_links", ["user_id"], unique=False)
    op.add_column("vehicle_clusters", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        "vehicle_clusters",
        sa.Column("favourite", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "vehicle_clusters", sa.Column("hidden", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    op.add_column(
        "vehicle_clusters",
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_clusters", "notes")
    op.drop_column("vehicle_clusters", "hidden")
    op.drop_column("vehicle_clusters", "favourite")
    op.drop_column("vehicle_clusters", "archived_at")
    op.drop_index(op.f("ix_relist_links_user_id"), table_name="relist_links")
    op.drop_index(op.f("ix_relist_links_old_id"), table_name="relist_links")
    op.drop_index(op.f("ix_relist_links_new_id"), table_name="relist_links")
    op.drop_table("relist_links")
    op.drop_index(
        "uq_decisions_active",
        table_name="duplicate_decisions",
        postgresql_where=sa.text("superseded_at IS NULL"),
    )
    op.drop_index(op.f("ix_duplicate_decisions_user_id"), table_name="duplicate_decisions")
    op.drop_index(op.f("ix_duplicate_decisions_right_id"), table_name="duplicate_decisions")
    op.drop_index(op.f("ix_duplicate_decisions_left_id"), table_name="duplicate_decisions")
    op.drop_table("duplicate_decisions")
    op.drop_index(op.f("ix_duplicate_candidates_user_id"), table_name="duplicate_candidates")
    op.drop_index(op.f("ix_duplicate_candidates_right_id"), table_name="duplicate_candidates")
    op.drop_index(op.f("ix_duplicate_candidates_left_id"), table_name="duplicate_candidates")
    op.drop_table("duplicate_candidates")
    op.drop_table("listing_fingerprints")
    op.drop_index(op.f("ix_cluster_operations_user_id"), table_name="cluster_operations")
    op.drop_table("cluster_operations")
    # ### end Alembic commands ###
